export * from './degree.service';
export * from './doctor-chamber.service';
export * from './doctor-degree.service';
export * from './doctor-profile.service';
export * from './doctor-specialization.service';
export * from './otp.service';
export * from './speciality.service';
export * from './specialization.service';
export * from './user-accounts.service';
